language: node_js
node_js: 8

sudo: enabled

cache:
  directories:
    - node_modules

before_install:
  - . ci/travis/before_install.sh

install:
  - . ci/travis/install.sh

before_script:
  - . ci/travis/before_script.sh

script:
  - . ci/travis/script.sh
